#
# Autogenerated by Thrift Compiler (0.18.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
ERR_UNDEFINED = 1300
ERR_AUTH_NOPASS = 1301
ERR_TIMEOUT = 506
ERR_NO_MATCH_PARAM = 401
ERR_TABLE_EXIST = 409
ERR_DATA_NOEXIST = 410
ERR_TABLE_NOEXIST = 411
ERR_COLUMN_NOEXIST = 412
ERR_IDX_NOEXIST = 413
